baseURL = 'https://hnp.moscow/'
languageCode = 'ru-ru'
title = 'Хромченков и партнеры - Юридические услуги в Москве'
defaultContentLanguage = 'ru'
enableRobotsTXT = true

[params]
  description = "Юридические услуги для граждан и бизнеса в Москве. Земельные, жилищные, семейные и наследственные дела, судебное представительство и консалтинг."
  author = "Хромченков и партнеры"
  phone = "+7 (926) 279-63-50"
  email = "info@hnp.moscow"

[build]
  writeStats = true
  useResourceCacheWhen = 'fallback'

[services]
  [services.googleAnalytics]
    id = ''

[minify]
  disableXML = true
  minifyOutput = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
